### PR TITLE
Update README file

### PR DESCRIPTION
**Pull request by RutiRozenberg**
Update a README file for this specific React app instead of the previous file that described the React app in general.

### CODE REVIEW

**Review by DvoraShechter1 — APPROVED** [review]
wonderful

**Review by DvoraShechter1 — APPROVED** [review]
excellent

**Review by DvoraShechter1 — APPROVED** [review]

**Review by DvoraShechter1 — CHANGES_REQUESTED** [review]
I would appreciate it if you added a link to the active site.
Other than that - it looks perfect!

**Comment by RutiRozenberg** [comment]
I have addressed all the requested changes in this pull request . Additionally, I have resolved a bug in the Comment.js file.
I opened a new pull request - #8 .

**Pull request merged**
